### ISSUE TITLE
In pfnet_faedge_head.py

### ISSUE THREAD

**Issue by Billy-ZTB** [angiecao/CPNet#1]
In class SobelEdge_Simple, you defined 4 sobel kernels for 4directions, but in the forward function, edge45 and edge135 weren't calculated with the corresponding kernels.
![image](https://github.com/user-attachments/assets/97782df5-1206-4aab-a75c-1f3db22414f9)

**Comment by angiecao** [comment]
Thank you for your correction, it has been corrected. But you can rest assured that this error will not have a significant impact on the final result, because the horizontal (sobel_kernel0) and vertical (sobel_kernel90) directions are still present.

**Comment by Billy-ZTB** [comment]
Thanks.
